Check git revision on test instance

diff --git a/scripts/wercker/check-connectivity b/scripts/wercker/check-connectivity
--- a/scripts/wercker/check-connectivity
+++ b/scripts/wercker/check-connectivity
@@ -23,6 +23,19 @@ function terminate_failing_instances () {
   echo $INSTANCE_IDS | xargs -n 1 $SCRIPTS/test-instance/terminate
 }
 
+function check_revision () {
+  INSTANCE=$1
+  HOST=$(echo $INSTANCE | awk ' {print $2}')
+  REMOTE_REVISION=$($SCRIPTS/test-instance/ssh $HOST 'GIT_DIR=/opt/koding/.git git rev-parse HEAD')
+
+  if [ $REMOTE_REVISION != $REVISION ]; then
+    echo "error: revision does not match on $INSTANCE"
+    return 1
+  fi
+
+  return 0
+}
+
 function check_connectivity () {
   INSTANCE=$1
   INSTANCE_ID=$(echo $INSTANCE | awk '{print $1}')
@@ -70,6 +83,7 @@ truncate --size 0 $INSTANCE_DATA_FILE
 
 for INSTANCE in $INSTANCES; do
   (
+    check_revision $INSTANCE || fail_instance $INSTANCE
     check_connectivity $INSTANCE  8090 1m 5 || fail_instance $INSTANCE
     check_connectivity $INSTANCE 42424 1m 5 || fail_instance $INSTANCE
     health_check $INSTANCE || fail_instance $INSTANCE
