Replace spaces with tabs
Signed-off-by: Sonmez Kartal <sonmez@koding.com>

diff --git a/scripts/bootstrap-container b/scripts/bootstrap-container
--- a/scripts/bootstrap-container
+++ b/scripts/bootstrap-container
@@ -31,13 +31,13 @@ function is_ready() {
 
 function run() {
 	case "$1" in
-		backend)
-			run_backend
-			;;
-		*)
-			echo 'error: unknown service'
-			exit 1
-			;;
+	backend)
+		run_backend
+		;;
+	*)
+		echo 'error: unknown service'
+		exit 1
+		;;
 	esac
 }
 
